[package]
name = "varlink-cli"
version = "4.1.1"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"

license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink-cli"
repository = "https://github.com/varlink/rust"
description = "varlink command line tool"

[[bin]]
name = "varlink"
path = "src/main.rs"

[dependencies]
varlink = { version = "7", path = "../varlink" }
varlink_stdinterfaces = { version = "7", path = "../varlink_stdinterfaces" }
varlink_parser = { version = "4", path = "../varlink_parser" }
serde = "1"
serde_json = "1"
clap = "2"
chainerror = "0.4.2"
colored_json = "2"
itertools = "0"

[dev-dependencies]
escargot = "0.3"
